In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
dataset=pd.read_csv(r"C:\Users\beher\Downloads\Restaurant_Reviews (1).tsv",sep="\t")


In [3]:

import re 
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [4]:
corpus=[]

In [5]:
for i in range(0,1000):
    review=re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review=review.lower()
    review=review.split()
    ps=PorterStemmer()
    review=[ps.stem(word) for word  in review if not word in set (stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

In [181]:

from sklearn.feature_extraction.text import TfidfVectorizer

cv=TfidfVectorizer(
    max_features=3000,
    ngram_range=(1,2)
)


In [182]:

x=cv.fit_transform(corpus).toarray()

y=dataset.iloc[:,1].values


from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)




# Decision tree

In [183]:
from sklearn.tree import DecisionTreeClassifier

dt=DecisionTreeClassifier(criterion='gini',max_depth=None,min_samples_leaf=1,min_samples_split=5)

dt.fit(x_train, y_train)

y_pred=dt.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)
print(ac)
print(cm)

bias=dt.score(x_train, y_train)
print(bias)
var=dt.score(x_test,y_test)
print(var)


0.695
[[78 19]
 [42 61]]
0.98625
0.695


# logistic regression

In [184]:
from sklearn.linear_model import LogisticRegression

In [185]:
lr=LogisticRegression(C=1)
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)


In [186]:
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)
print("accuracy ",ac)
print(cm)

bias=lr.score(x_train, y_train)
print("bias",bias)
var=lr.score(x_test,y_test)
print("var",var)

accuracy  0.76
[[85 12]
 [36 67]]
bias 0.96125
var 0.76


# NAIBE bayes 

In [187]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB(alpha=2)


In [188]:
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)


In [189]:
ac=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
print("Accuracy score ",ac)
print(cm)
bias=nb.score(x_train, y_train)
print("bias",bias)
var=nb.score(x_test,y_test)
print("var",var)

Accuracy score  0.78
[[79 18]
 [26 77]]
bias 0.9625
var 0.78


# gaussian 

In [190]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB(var_smoothing=0.4)


In [191]:
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)


In [192]:
ac=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
print("Accuracy score ",ac)
print(cm)
bias=nb.score(x_train, y_train)
print("bias",bias)
var=nb.score(x_test,y_test)
print("var",var)

Accuracy score  0.775
[[79 18]
 [27 76]]
bias 0.9725
var 0.775


# KNN

In [193]:
from sklearn.neighbors import KNeighborsClassifier

In [194]:
knn=KNeighborsClassifier(n_neighbors=7,metric='euclidean',weights='distance')

In [195]:
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [196]:
ac=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
print("accuracy",ac)
print(cm)

accuracy 0.7
[[82 15]
 [45 58]]


In [197]:
bias=knn.score(x_train, y_train)
print("bias",bias)
var=knn.score(x_test,y_test)
print("var",var)

bias 0.9925
var 0.7


# svm

In [198]:
from sklearn.svm import SVC


In [199]:
svc=SVC(kernel='rbf',C=10,random_state=0)

In [200]:
svc.fit(x_train,y_train)


SVC(C=10, random_state=0)

In [201]:
y_pred=svc.predict(x_test)

In [202]:
ac=accuracy_score(y_test,y_pred)
print("accuracy",ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

accuracy 0.79
[[83 14]
 [28 75]]


In [203]:
bias=svc.score(x_train, y_train)
print("bias",bias)
var=svc.score(x_test,y_test)
print("var",var)

bias 0.9925
var 0.79


# Random forest

In [204]:
from sklearn.ensemble import RandomForestClassifier

In [205]:
rf=RandomForestClassifier(
      n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=0
)

In [206]:
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [207]:
ac=accuracy_score(y_test,y_pred)
print("accuracy",ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

accuracy 0.75
[[87 10]
 [40 63]]


In [208]:
bias=rf.score(x_train, y_train)
print("bias",bias)
var=rf.score(x_test,y_test)
print("var",var)

bias 0.9925
var 0.75


# XGBBOST

In [209]:
from xgboost import XGBClassifier

In [210]:
xgb=XGBClassifier(learning_rate=0.1,
    max_depth=5,
    n_estimators=200,
    random_state=0,
    eval_metric='logloss')

In [211]:
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)


In [212]:
ac=accuracy_score(y_test,y_pred)
print("accuracy",ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

accuracy 0.705
[[87 10]
 [49 54]]


In [213]:
bias=xgb.score(x_train, y_train)
print("bias",bias)
var=xgb.score(x_test,y_test)
print("var",var)

bias 0.8675
var 0.705


# light gbm

In [214]:
from lightgbm import LGBMClassifier

In [215]:
lgb=LGBMClassifier(
    learning_rate= 0.01, max_depth= 3, n_estimators= 200
)

In [216]:
import warnings
warnings.filterwarnings('ignore')
lgb.fit(x_train,y_train)
y_pred=lgb.predict(x_test)

[LightGBM] [Info] Number of positive: 397, number of negative: 403
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000432 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 359
[LightGBM] [Info] Number of data points in the train set: 800, number of used features: 28
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.496250 -> initscore=-0.015000
[LightGBM] [Info] Start training from score -0.015000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [217]:
ac=accuracy_score(y_test,y_pred)
print("accuracy",ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

accuracy 0.64
[[94  3]
 [69 34]]


In [218]:
bias=lgb.score(x_train, y_train)
print("bias",bias)
var=lgb.score(x_test,y_test)
print("var",var)

bias 0.71125
var 0.64


# model ranking table

In [219]:
import pandas as pd

results = {
    "Model": [
        "MultinomialNB",
        "Logistic Regression",
        "GaussianNB",
        "SVM",
        "Random Forest",
        "KNN",
        "XGBoost",
        "Decision Tree",
        "LightGBM"
    ],
    
    "Accuracy": [
        0.775,
        0.755,
        0.750,
        0.745,
        0.740,
        0.710,
        0.705,
        0.700,
        0.635
    ],
    
    "Bias Score": [
        0.9375,
        0.94625,
        0.94375,
        0.99625,
        0.99625,
        0.99625,
        0.875,
        0.985,
        0.70875
    ],
    
    "Variance Score": [
        0.775,
        0.755,
        0.750,
        0.745,
        0.740,
        0.710,
        0.705,
        0.700,
        0.635
    ]
}

df = pd.DataFrame(results)

df = df.sort_values(
    by="Accuracy",
    ascending=False
).reset_index(drop=True)

df.index = df.index + 1
df.index.name = "Rank"

print(df)

                    Model  Accuracy  Bias Score  Variance Score
Rank                                                           
1           MultinomialNB     0.775     0.93750           0.775
2     Logistic Regression     0.755     0.94625           0.755
3              GaussianNB     0.750     0.94375           0.750
4                     SVM     0.745     0.99625           0.745
5           Random Forest     0.740     0.99625           0.740
6                     KNN     0.710     0.99625           0.710
7                 XGBoost     0.705     0.87500           0.705
8           Decision Tree     0.700     0.98500           0.700
9                LightGBM     0.635     0.70875           0.635


# count vectorizer 

In [220]:
from sklearn.feature_extraction.text import CountVectorizer

In [221]:
cv=CountVectorizer()

In [222]:
x=cv.fit_transform(corpus).toarray()

In [223]:
y=dataset.iloc[:,1].values

In [224]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

# Multinomial 

In [225]:
nb=MultinomialNB(alpha=0.5)
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)

In [226]:
ac=accuracy_score(y_test,y_pred)
print(ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.775
[[73 24]
 [21 82]]


In [227]:
bias=nb.score(x_train,y_train)
var=nb.score(x_test,y_test)
print(bias)
print(var)

0.945
0.775


# Logistic reg 

In [228]:
lr=LogisticRegression(C=1)
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [229]:
ac=accuracy_score(y_test,y_pred)
print(ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.71
[[76 21]
 [37 66]]


In [230]:
bias=lr.score(x_train,y_train)
var=lr.score(x_test,y_test)
print(bias)
print(var)

0.9575
0.71


# GaussianNB

In [231]:
from sklearn.naive_bayes import GaussianNB

In [232]:
nb=GaussianNB(var_smoothing=0.03792)

In [233]:
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)


In [234]:
ac=accuracy_score(y_test,y_pred)
print(ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.76
[[62 35]
 [13 90]]


In [235]:
bias=nb.score(x_train,y_train)
var=nb.score(x_test,y_test)
print(bias)
print(var)

0.93875
0.76


# SVM

In [236]:
from sklearn.svm import SVC


In [237]:
svc=SVC(kernel='rbf',C=10)

In [238]:
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)

In [239]:
ac=accuracy_score(y_test,y_pred)
print(ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.74
[[80 17]
 [35 68]]


In [240]:
bias=svc.score(x_train,y_train)
print(bias)
var=svc.score(x_test,y_test)
print(var)

0.995
0.74


# KNN 

In [241]:
from sklearn.neighbors import KNeighborsClassifier

In [242]:
knn=KNeighborsClassifier()

In [243]:

knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [244]:
ac=accuracy_score(y_test,y_pred)
print(ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.645
[[84 13]
 [58 45]]


In [245]:
bias=knn.score(x_train,y_train)
print(bias)
var=knn.score(x_test,y_test)
print(var)

0.775
0.645


# Decision tree 

In [246]:
from sklearn.tree import DecisionTreeClassifier

In [247]:
dt=DecisionTreeClassifier(

    criterion='entropy', max_depth= 15, min_samples_leaf= 1, min_samples_split= 2
)

In [248]:
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [249]:
ac=accuracy_score(y_test,y_pred)
print(ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.71
[[93  4]
 [54 49]]


In [250]:
bias=dt.score(x_train,y_train)
print(bias)
var=dt.score(x_test,y_test)
print(var)

0.80375
0.71


# random forest 

In [251]:
from sklearn.ensemble import RandomForestClassifier

In [252]:
rf=RandomForestClassifier(
    max_depth= 20, min_samples_leaf= 2, min_samples_split= 2, n_estimators= 300
)

In [253]:
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)


In [254]:
ac=accuracy_score(y_test,y_pred)
print(ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.755
[[90  7]
 [42 61]]


In [255]:
bias=rf.score(x_train,y_train)
print(bias)
var=rf.score(x_test,y_test)
print(var)

0.8475
0.755


# XGBOOST

In [256]:
from xgboost import XGBClassifier

In [257]:
xbg=XGBClassifier()

In [258]:
xbg.fit(x_train,y_train)
y_pred=xbg.predict(x_test)

In [259]:
ac=accuracy_score(y_test,y_pred)
print(ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.72
[[83 14]
 [42 61]]


In [260]:
bias=xbg.score(x_train,y_train)
print(bias)
var=xbg.score(x_test,y_test)
print(var)

0.86
0.72


# LIGHTGBM

In [261]:
from lightgbm import LGBMClassifier

In [262]:
lgb=LGBMClassifier()

In [263]:
lgb.fit(x_train,y_train)
y_pred=lgb.predict(x_test)

[LightGBM] [Info] Number of positive: 397, number of negative: 403
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000394 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 69
[LightGBM] [Info] Number of data points in the train set: 800, number of used features: 27
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.496250 -> initscore=-0.015000
[LightGBM] [Info] Start training from score -0.015000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf


In [264]:
ac=accuracy_score(y_test,y_pred)
print(ac)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.66
[[84 13]
 [55 48]]


In [265]:
bias=lgb.score(x_train,y_train)
print(bias)
var=lgb.score(x_test,y_test)
print(var)

0.7275
0.66


# model ranking table countvec

In [266]:
import pandas as pd

results = {
    "Model": [
        "MultinomialNB",
        "GaussianNB",
        "SVM",
        "Random Forest",
        "XGBoost",
        "Logistic Regression",
        "Decision Tree",
        "LightGBM",
        "KNN"
    ],

    "Accuracy": [
        0.775,
        0.760,
        0.740,
        0.740,
        0.720,
        0.710,
        0.710,
        0.660,
        0.645
    ],

    "Bias Score": [
        0.9450,
        0.93875,
        0.9950,
        0.83875,
        0.8600,
        0.9575,
        0.80375,
        0.7275,
        0.7750
    ],

    "VAR Score": [
        0.775,
        0.760,
        0.740,
        0.740,
        0.720,
        0.710,
        0.710,
        0.660,
        0.645
    ]
}

df = pd.DataFrame(results)

df["Gap"] = round(
    (df["Bias Score"] - df["VAR Score"]) * 100,
    2
)

df = df.sort_values(
    by="Accuracy",
    ascending=False
).reset_index(drop=True)

df.index = df.index + 1
df.index.name = "Rank"

print(df)

                    Model  Accuracy  Bias Score  VAR Score    Gap
Rank                                                             
1           MultinomialNB     0.775     0.94500      0.775  17.00
2              GaussianNB     0.760     0.93875      0.760  17.87
3                     SVM     0.740     0.99500      0.740  25.50
4           Random Forest     0.740     0.83875      0.740   9.88
5                 XGBoost     0.720     0.86000      0.720  14.00
6     Logistic Regression     0.710     0.95750      0.710  24.75
7           Decision Tree     0.710     0.80375      0.710   9.38
8                LightGBM     0.660     0.72750      0.660   6.75
9                     KNN     0.645     0.77500      0.645  13.00
